### ISSUE TITLE
Set up a venue for localizers

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/community-localization#3]
We should have a place for localizers to be able to coordinate with each other. We should _also_ have a place where we can send announcements to all localizers. This might be a separate mailing list, or an `#announcements` channel on a localization Discord/Zulip/etc. It's important to be able to easily check on the health of the localization teams as well as notify them when major changes are coming and need translation.

Pontoon does show users when there's new stuff to be translated but for low-volume things like the website they'll typically

We could potentially have a `#new-translations` channel that has a bot posting any new strings that need updating. This could simply be hook that listens to git changes, but it could also be better.

**Comment by XAMPPRocky** [comment]
> We could potentially have a #new-translations channel that has a bot posting any new strings that need updating. This could simply be hook that listens to git changes, but it could also be better.

I think this would be easiest if it was implemented as a GitHub Action on the website repo, triggered whenever pontoon commits. Then we don't have to do any additional setup of a bot somewhere. We could also have it easily create an issue, but I think just posting in a chat would be enough to start.

If I had a preference for chat platform it would be Zulip, one good reason is that it offers email notifications for channels, so you don't have to keep the chat client always open to stay informed like you do with Discord, which makes it easier for people to stay in the loop.

**Comment by Manishearth** [comment]
@XAMPPRocky you misunderstand, this is about whenever there are new _English_ strings, which Pontoon doesn't commit. But yes, a github action that listens for changes to the `locales/en` folder is what we're looking for.

**Comment by XAMPPRocky** [comment]
Since we have set up zulip, should we close this issue and create a new issue for a translation/pontoon bot?

**Comment by Manishearth** [comment]
Yep
